name: families
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  http: ^1.2.0
  image_picker: ^1.0.7
  intl: ^0.18.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

# flutter_launcher_icons:
#   android: true
#   ios: true
#   image_path: "assets/images/icon.png"
#   remove_alpha_ios: true
flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf

  assets:
    - assets/images/

flutter_intl:
  enabled: true
