name: families
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter_launcher_icons: ^0.13.1
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  image_picker: ^1.0.7
  intl: ^0.19.0
  json_annotation: ^4.9.0
  mime: ^1.0.5
  onesignal_flutter: ^5.2.2
  permission_handler: ^11.3.1
  pinput: ^5.0.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  photo_view: ^0.15.0

dev_dependencies:
  build_runner: ^2.0.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  remove_alpha_ios: true

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: UniqueLight
      fonts:
        - asset: assets/fonts/UniqueLight.otf

    - family: UniqueBold
      fonts:
        - asset: assets/fonts/UniqueBold.otf

  assets:
    - assets/images/
    - assets/images/icons/

flutter_intl:
  enabled: true
